services:
  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: npm install && npm run build # Install dependencies before building
    startCommand: npm start
    plan: free
    serviceDetails:
      ports:
        - port: 3000

  - type: web
    name: backend
    env: docker
    dockerfilePath: ./src/backend/Dockerfile
    buildCommand: pip install -r requirements.txt # Assuming this is a Flask app
    startCommand: flask run --host=0.0.0.0
    plan: free
    serviceDetails:
      ports:
        - port: 5000
